image: python:3.9


stages:
    - build
    - test

before_script:
    - python --version

build-job:
    stage: build
    script:
        - echo "Installig packages ...."
        - echo "Building artifact ..."
        - git archive --format zip --output artifact.zip HEAD


lintest:
    stage: test
    script:
        - echo "Starting linters ..."
        - pip install flake8
        - flake8 src/data/analyze_data.py     


artifacts:
    paths:
        - artifact.zip   