image: python:3.9

stages:
  - build
  - test

before_script:
  - python --version

build-job:
  stage: build
  script:
    - echo "Installing packages ..."
    - tar -czf repo.tar.gz .
  artifacts:
    paths:
      - repo.tar.gz

lintest:
  stage: test
  script:
    - echo "Starting linters ..."
    - pip install flake8
    - flake8 src/data/analyze_data.py